/* eslint-disable prettier/prettier */

export interface LoginData{
  correo:string,
  password:string,
}

export interface LoadingFicha{
  id_ficha:string,
  id_user:string,
  token:string,
}

/*
export interface User {
  id:string,
  username: string;
  correo: string;
  imagen: string;
  password:string;
  estadoMx:string;
  sexo:string;
  edad:number;
  code:string;
  status:string;
  state:boolean;
  rol:string;
  fichas_guardadas:any[];
  reportes:any[];
}
*/

export interface LoginResponse{
  usuario:User;
  token:string;
  id:    string;
}



// Generated by https://quicktype.io

export interface User {
  usuario: Usuario;
}

export interface Usuario {
  _id:              string;
  username:         string;
  fotoPerfil:       string;
  correo:           string;
  password:         string;
  estadoMx:         string;
  sexo:             string;
  edad:             number;
  code:             string;
  status:           string;
  state:            boolean;
  imagen:           string;
  rol:              string;
  fichas_guardadas: string[];
  reportes:         any[];
  __v:              number;
}


