/* eslint-disable prettier/prettier */

export interface LoginData{
  correo:string,
  password:string,
}

export interface RegisterData{
  usuario:string,
  correo:string,
  contraseña:string,
  estado:string,
  sexo:string,
  edad:string,
}


export interface LoadingFicha{
  fichaID?:string,
  idUsuario?:string,
  tokenUser:string,
}

export interface LoginResponse{
  usuario:User;
  token:string;
  id:    string;
}

// Generated by https://quicktype.io

export interface User {
  _id:              string;
  username:         string;
  correo:           string;
  imagen:           string;
  password:         string;
  estadoMx:         string;
  sexo:             string;
  edad:             number;
  code:             string;
  status:           string;
  state:            boolean;
  rol:              string;
  fichas_guardadas: any[];
  reportes:         any[];
  __v:              number;
}




// Generated by https://quicktype.io


